import numpy as np

# Random Number Generator
RNG = np.random.default_rng()

# Employee Constants
PERFORMANCE_INCREASE_RATE = 0.01
PERFORMANCE_DECREASE_RATE = 0.02

# Promotion Weights for Combining Factors
PERFORMACE_LEVEL_WEIGHT = .15
POSITION_EXPERIENCE_WEIGHT = .35
IDENTITY_SIMILARITY_WEIGHT = .5

# Hiring Constants
HIRING_HOMOPHILY_WEIGHT = IDENTITY_SIMILARITY_WEIGHT

# Bias Constants
MAN_BIAS = 0.5
WOMAN_BIAS = 2
LEVEL_BIAS_COEFFICIENT = 0.25
BIAS_DECAY_RATE = 0.9

# Maternity Leave Constants
MATERNITY_LEAVE = 0.0075
MATERNITY_RETURN = 0.8
MATERNITY_BIAS = 0.5

# Simulation Constants
LEAVE_RATE = 0.01
IDENTITIES = ["M", "F"]
IDENTITY_POPULATION_PERCENTAGES = {"M": 0.6, "F": 0.4}
LEVEL_POPULATIONS = [50, 25, 10, 5]
NUM_LEVELS = 4
FIRE_RATE_COEFFICIENT = 0.01
BIAS_RATE_COEFFICIENT = 0.001